# Generated by Django 2.1.5 on 2020-04-02 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200402_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontent',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='任務開始時間'),
        ),
    ]
